# Generated by Django 6.0.2 on 2026-05-12 16:18

import assets_reporting.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aid_management', '0002_aidapplication_supporting_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(verbose_name='تاريخ انعقاد اللجنة')),
                ('meeting_number', models.PositiveIntegerField(verbose_name='رقم الاجتماع')),
                ('official_document', models.FileField(blank=True, null=True, upload_to='minutes/%Y/', verbose_name='النسخة الموقعة والممسوحة ضوئياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_applications', models.ManyToManyField(to='aid_management.aidapplication', verbose_name='الطلبات المعتمدة')),
                ('attendees', models.ManyToManyField(related_name='attended_meetings', to=settings.AUTH_USER_MODEL)),
                ('head_of_committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محضر اجتماع لجنة',
                'verbose_name_plural': 'محاضر اجتماعات اللجان',
            },
        ),
        migrations.CreateModel(
            name='DisbursementVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار الصرف'), ('PAID', 'تم الصرف'), ('EXPIRED', 'منتهي الصلاحية')], default='PENDING', max_length=10)),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('verification_hash', models.CharField(max_length=100, unique=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='aid_management.budgetallocation', verbose_name='التخصيص المرتبط')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aid_management.aidapplication')),
            ],
            options={
                'verbose_name': 'قسيمة صرف',
                'verbose_name_plural': 'قسائم الصرف',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=assets_reporting.models.get_file_path, verbose_name='الملف المرفق')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق من صحته')),
                ('verification_note', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='aid_management.aidapplication', verbose_name='الطلب المرتبط')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_reporting.documenttype', verbose_name='نوع المستند')),
            ],
            options={
                'verbose_name': 'مستند مرفق',
                'verbose_name_plural': 'مستندات الطلبات',
            },
        ),
        migrations.CreateModel(
            name='OfficialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf_version', models.FileField(blank=True, null=True, upload_to='reports/archives/%Y/')),
                ('verification_qr', models.ImageField(blank=True, null=True, upload_to='reports/qr/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_report', to='aid_management.aidapplication')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير رسمي',
                'verbose_name_plural': 'أرشيف التقارير الرسمية',
            },
        ),
        migrations.CreateModel(
            name='SocialResearchForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('OWN', 'تمليك'), ('RENT', 'إيجار'), ('OLD_RENT', 'إيجار قديم')], max_length=20, verbose_name='نوع السكن')),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='القيمة الإيجارية')),
                ('researcher_opinion', models.TextField(verbose_name='رأي الباحث الاجتماعي وتوصيته')),
                ('researcher_name', models.CharField(max_length=255)),
                ('research_document', models.FileField(blank=True, null=True, upload_to='research_documents/%Y/', verbose_name='ملف البحث الميداني (Word/PDF)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_research', to='aid_management.aidapplication')),
            ],
            options={
                'verbose_name': 'استمارة بحث اجتماعي',
                'verbose_name_plural': 'استمارات البحوث الاجتماعية',
            },
        ),
    ]
