# Generated by Django 6.0.2 on 2026-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementvoucher',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/qr/', verbose_name='رمز QR'),
        ),
    ]
