# Generated by Django 6.0.2 on 2026-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_reporting', '0002_disbursementvoucher_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم النموذج')),
                ('file', models.FileField(upload_to='system_templates/', verbose_name='ملف النموذج')),
                ('role_required', models.CharField(choices=[('S', 'طالب'), ('R', 'مُراجع (باحث اجتماعي)'), ('C', 'رئيس/عضو لجنة'), ('A', 'مدير النظام'), ('D', 'مراقب/مدقق')], max_length=1, verbose_name='الدور المخصص له')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نموذج نظام',
                'verbose_name_plural': 'نماذج النظام المخصصة',
            },
        ),
    ]
