# Generated by Django 6.0.2 on 2026-03-08 15:03

import accounts.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم / البرنامج')),
                ('code', models.CharField(help_text='مثال: CS, BIO, MATH', max_length=10, unique=True, verbose_name='كود البرنامج')),
                ('description', models.TextField(blank=True, verbose_name='وصف البرنامج')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح حالياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'برنامج أكاديمي',
                'verbose_name_plural': 'البرامج الأكاديمية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='مثال: UG_5985405@science.tanta.edu.eg', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_university_email', message='يجب استخدام البريد الجامعي الرسمي لجامعة طنطا (علوم)، مثال: UG_5945090@science.tanta.edu.eg', regex='^UG_\\d+@science\\.tanta\\.edu\\.eg$')], verbose_name='البريد الإلكتروني الجامعي')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(help_text='مكون من 14 رقماً.', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقماً بالضبط.', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('role', models.CharField(choices=[('S', 'طالب'), ('R', 'مُراجع'), ('C', 'رئيس لجنة'), ('D', 'المراقب'), ('A', 'مدير نظام')], db_index=True, default='S', max_length=1, verbose_name='نوع المستخدم')),
                ('is_verified', models.BooleanField(default=False, help_text='تشير إلى ما إذا كان المستخدم قد قام بتفعيل البريد الإلكتروني.', verbose_name='حالة التوثيق')),
                ('image', models.ImageField(blank=True, help_text='صورة شخصية للمستخدم (اختياري)', null=True, upload_to='profile_images/%Y/%m/', validators=[accounts.models.validate_signature_image], verbose_name='صورة الملف الشخصي')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeHeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(help_text='مثال: لجنة المساعدات المالية، لجنة شؤون الطلاب', max_length=150, verbose_name='اسم اللجنة')),
                ('authority_level', models.PositiveSmallIntegerField(default=1, help_text='مستوى الإدارة (1 هو الأدنى، 5 هو الأعلى)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='مستوى الصلاحية')),
                ('signature_image', models.ImageField(blank=True, help_text='تُستخدم لاعتماد المستندات إلكترونياً (PNG أو JPG، بحد أقصى 5MB)', null=True, upload_to='signatures/heads/%Y/%m/', validators=[accounts.models.validate_signature_image], verbose_name='صورة التوقيع الرسمي')),
                ('is_active_head', models.BooleanField(default=True, verbose_name='رئيس لجنة حالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='committee_head_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
                ('managed_programs', models.ManyToManyField(blank=True, help_text='الأقسام الأكاديمية التي تندرج تحت اختصاص هذه اللجنة', related_name='committee_heads', to='accounts.program', verbose_name='الأقسام المشرف عليها')),
            ],
            options={
                'verbose_name': 'ملف رئيس اللجنة',
                'verbose_name_plural': 'ملفات رؤساء اللجان',
            },
        ),
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة مختصرة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='auditor_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
                ('assigned_programs', models.ManyToManyField(blank=True, related_name='auditors', to='accounts.program', verbose_name='الأقسام المسئول عن تدقيقها')),
            ],
            options={
                'verbose_name': 'ملف المراقب',
                'verbose_name_plural': 'ملفات المراقبين',
            },
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_rank', models.CharField(choices=[('PROF', 'أستاذ دكتور'), ('ASSOC', 'أستاذ مشارك'), ('ASST', 'أستاذ مساعد'), ('LECT', 'مدرس / محاضر')], default='LECT', max_length=5, verbose_name='الدرجة العلمية')),
                ('specialization', models.CharField(help_text='مثال: الكيمياء العضوية، فيزياء الجوامد', max_length=100, verbose_name='التخصص الدقيق')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة مختصرة')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='مقر المكتب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_programs', models.ManyToManyField(blank=True, related_name='reviewers', to='accounts.program', verbose_name='الأقسام المسئول عن مراجعتها')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'R'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المُراجع',
                'verbose_name_plural': 'ملفات المُراجعين',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='الرقم الجامعي')),
                ('level', models.IntegerField(choices=[(1, 'المستوى الأول'), (2, 'المستوى الثاني'), (3, 'المستوى الثالث'), (4, 'المستوى الرابع')], default=1, verbose_name='المستوى الدراسي')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='المعدل التراكمي (GPA)')),
                ('phone', models.CharField(help_text='مثال: 010xxxxxxxx', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_egyptian_phone', message='رقم الهاتف يجب أن يكون رقم موبايل مصري صحيح (11 رقم) يبدأ بـ 010، 011، 012، أو 015.', regex='^01[0125]\\d{8}$')], verbose_name='رقم الموبايل المصري')),
                ('address', models.TextField(blank=True, verbose_name='عنوان السكن بالتفصيل')),
                ('disability_status', models.BooleanField(default=False, verbose_name='ذوي الاحتياجات الخاصة')),
                ('HasPreviousSupport', models.BooleanField(default=False, verbose_name='هل حصلت على دعم سابق؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('program', models.ForeignKey(help_text='القسم الدراسي الذي يتبعه الطالب', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.program', verbose_name='القسم الأكاديمي')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'ملف الطالب',
                'verbose_name_plural': 'ملفات الطلاب',
                'ordering': ['-gpa', 'student_id'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'national_id'], name='accounts_us_email_765f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_verified'], name='accounts_us_role_120ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='committeeheadprofile',
            index=models.Index(fields=['is_active_head', 'authority_level'], name='accounts_co_is_acti_e3a83d_idx'),
        ),
        migrations.AddIndex(
            model_name='committeeheadprofile',
            index=models.Index(fields=['committee_name'], name='accounts_co_committ_66fe16_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorprofile',
            index=models.Index(fields=['user'], name='accounts_au_user_id_d5a7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerprofile',
            index=models.Index(fields=['user', 'academic_rank'], name='accounts_re_user_id_ae173b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerprofile',
            index=models.Index(fields=['specialization'], name='accounts_re_special_5d6645_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['program', 'level'], name='accounts_st_program_f0c938_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['gpa'], name='accounts_st_gpa_9b1c67_idx'),
        ),
    ]
