# Generated by Django 6.0.2 on 2026-04-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(blank=True, help_text='القسم الدراسي الذي يتبعه الطالب', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.program', verbose_name='القسم الأكاديمي'),
        ),
    ]
