# Generated by Django 6.0.2 on 2026-04-07 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='مثال: UG_5985405@science.tanta.edu.eg', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_university_email', message='يجب استخدام البريد الجامعي الرسمي لجامعة طنطا (علوم)، مثال: UG_5945090@science.tanta.edu.eg', regex='^(?i)UG_\\d+@science\\.tanta\\.edu\\.eg$')], verbose_name='البريد الإلكتروني الجامعي'),
        ),
    ]
