# Generated by Django 6.0.2 on 2026-04-07 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='مثال: 010xxxxxxxx', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_egyptian_phone', message='رقم الهاتف يجب أن يكون رقم موبايل مصري صحيح (11 رقم) يبدأ بـ 010، 011، 012، أو 015.', regex='^01[0125]\\d{8}$')], verbose_name='رقم الموبايل المصري'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='مثال: UG_5985405@science.tanta.edu.eg', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_university_email', message='يجب استخدام البريد الجامعي الرسمي لجامعة طنطا (علوم)، مثال: UG_5945090@science.tanta.edu.eg', regex='(?i)^UG_\\d+@science\\.tanta\\.edu\\.eg$')], verbose_name='البريد الإلكتروني الجامعي'),
        ),
    ]
