# Generated by Django 6.0.2 on 2026-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='تشير إلى ما إذا كان المستخدم قد قام بتفعيل البريد الإلكتروني.', verbose_name='حالة التوثيق'),
        ),
    ]
