# Generated by Django 6.0.2 on 2026-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
