# Generated by Django 6.0.2 on 2026-05-14 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_serialcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي (IBAN)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='مثال: بنك مصر، البنك الأهلي المصري', max_length=100, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_egyptian_phone', message='رقم الهاتف يجب أن يكون رقم موبايل مصري صحيح (11 رقم) يبدأ بـ 010، 011، 012، أو 015.', regex='^01[0125]\\d{8}$')], verbose_name='رقم المحفظة الإلكترونية'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wallet_provider',
            field=models.CharField(blank=True, help_text='مثال: فودافون كاش، اتصالات كاش، أمان', max_length=50, null=True, verbose_name='مزود المحفظة الإلكترونية'),
        ),
    ]
