# Generated by Django 6.0.2 on 2026-05-12 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aid_management', '0002_aidapplication_supporting_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'دخول'), ('LOGOUT', 'خروج'), ('FAILED', 'فشل دخول')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(verbose_name='بيانات المتصفح')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل وصول',
                'verbose_name_plural': 'سجلات الوصول',
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('SCORED', 'تم التقييم'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('DISBURSED', 'تم الصرف')], max_length=20, verbose_name='من حالة')),
                ('to_status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('SCORED', 'تم التقييم'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('DISBURSED', 'تم الصرف')], max_length=20, verbose_name='إلى حالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات التغيير')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='aid_management.aidapplication', verbose_name='الطلب')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'تاريخ حالة الطلب',
                'verbose_name_plural': 'سجلات تاريخ الحالات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255, verbose_name='سبب التغيير')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_management.supportcycle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(max_length=50, verbose_name='نوع الجدول')),
                ('entity_id', models.CharField(max_length=255, verbose_name='معرف السجل')),
                ('action', models.CharField(choices=[('CREATE', 'إضافة'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف')], max_length=10)),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='البيانات قبل')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='البيانات بعد')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التعديل')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم القائم بالإجراء')),
            ],
            options={
                'verbose_name': 'سجل بيانات',
                'verbose_name_plural': 'سجلات البيانات',
            },
        ),
        migrations.CreateModel(
            name='FinancialIntegrityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sum_of_allocations', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_balanced', models.BooleanField(default=True)),
                ('check_type', models.CharField(default='AUTOMATED_RECONCILIATION', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_management.supportcycle')),
            ],
            options={
                'verbose_name': 'سجل مطابقة مالية',
                'verbose_name_plural': 'سجلات المطابقة المالية',
            },
        ),
        migrations.CreateModel(
            name='ProcessActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, verbose_name='الإجراء الإداري')),
                ('cycle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(verbose_name='مبررات القرار')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل إجراء إداري',
                'verbose_name_plural': 'سجل الإجراءات الإدارية',
            },
        ),
        migrations.CreateModel(
            name='SystemOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(max_length=50, verbose_name='نوع التجاوز')),
                ('reason', models.TextField(verbose_name='السبب الإداري للتجاوز')),
                ('previous_state', models.JSONField(verbose_name='الحالة السابقة')),
                ('new_state', models.JSONField(verbose_name='الحالة الجديدة')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_management.aidapplication')),
            ],
            options={
                'verbose_name': 'سجل تجاوز نظام',
                'verbose_name_plural': 'سجلات التجاوزات الاستثنائية',
            },
        ),
    ]
