# Generated by Django 6.0.2 on 2026-04-10 11:34

import aid_management.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_serialcounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرف')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('SCORED', 'تم التقييم'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('DISBURSED', 'تم الصرف')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('financial_assessment', models.JSONField(blank=True, default=dict, validators=[aid_management.models.validate_financial_data], verbose_name='التقييم المالي')),
                ('committee_decision', models.TextField(blank=True, verbose_name='قرار اللجنة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.studentprofile', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب مساعدة',
                'verbose_name_plural': 'طلبات المساعدة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف الدورة')),
                ('serial_number', models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='رقم الدورة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الدورة')),
                ('academic_year', models.CharField(max_length=20, verbose_name='العام الدراسي')),
                ('semester', models.CharField(choices=[('FIRST', 'الفصل الأول'), ('SECOND', 'الفصل الثاني'), ('SUMMER', 'الفصل الصيفي')], max_length=10, verbose_name='الفصل الدراسي')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي الميزانية')),
                ('reserved_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الميزانية المحجوزة')),
                ('disbursed_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الميزانية المصروفة')),
                ('application_start_date', models.DateTimeField(verbose_name='تاريخ بداية التقديم')),
                ('application_end_date', models.DateTimeField(verbose_name='تاريخ نهاية التقديم')),
                ('review_start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بداية المراجعة')),
                ('review_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ نهاية المراجعة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('OPEN', 'مفتوح للتقديم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('CLOSED', 'مغلق'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('scoring_rules_snapshot', models.JSONField(blank=True, default=list, verbose_name='نسخة قواعد التقييم')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycles', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'دورة دعم',
                'verbose_name_plural': 'دورات الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف التخصيص')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('DISBURSED', 'تم الصرف'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المخصص')),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المصروف')),
                ('disbursement_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='aid_management.aidapplication', verbose_name='الطلب')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_allocations', to=settings.AUTH_USER_MODEL, verbose_name='تم الصرف بواسطة')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='aid_management.supportcycle', verbose_name='دورة الدعم')),
            ],
            options={
                'verbose_name': 'تخصيص ميزانية',
                'verbose_name_plural': 'تخصيصات الميزانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='aid_management.supportcycle', verbose_name='دورة الدعم'),
        ),
        migrations.CreateModel(
            name='CommitteeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف المراجعة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم')], default='DRAFT', max_length=20, verbose_name='حالة المراجعة')),
                ('conflict_of_interest', models.BooleanField(default=False, verbose_name='تعارض مصالح')),
                ('dimension_scores', models.JSONField(default=dict, help_text="مثال: {'income_tier': 10, 'gpa': 5}", verbose_name='درجات التقييم')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='المجموع الكلي')),
                ('qualitative_notes', models.TextField(blank=True, verbose_name='ملاحظات نوعية')),
                ('review_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت المراجعة')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='تم التقديم')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aid_management.aidapplication', verbose_name='الطلب')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'مراجعة لجنة',
                'verbose_name_plural': 'مراجعات اللجنة',
                'ordering': ['-review_timestamp'],
                'unique_together': {('application', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف القاعدة')),
                ('criteria_type', models.CharField(choices=[('INCOME_TIER', 'شريحة الدخل'), ('FAMILY_SIZE', 'عدد أفراد الأسرة'), ('GPA', 'المعدل التراكمي'), ('SPECIAL_CASES', 'الحالات الخاصة'), ('SOCIAL_RESEARCH', 'البحث الاجتماعي')], max_length=30, verbose_name='نوع المعيار')),
                ('condition', models.JSONField(help_text="مثال: {'min': 0, 'max': 3000}", verbose_name='شرط التطبيق')),
                ('description', models.TextField(blank=True, verbose_name='وصف القاعدة')),
                ('points', models.IntegerField(verbose_name='عدد النقاط')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='الوزن')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='aid_management.supportcycle', verbose_name='دورة الدعم')),
            ],
            options={
                'verbose_name': 'قاعدة تقييم',
                'verbose_name_plural': 'قواعد التقييم',
                'ordering': ['priority'],
                'indexes': [models.Index(fields=['cycle', 'criteria_type', 'is_active'], name='aid_managem_cycle_i_66d617_idx')],
                'unique_together': {('cycle', 'criteria_type')},
            },
        ),
        migrations.AddIndex(
            model_name='aidapplication',
            index=models.Index(fields=['student', 'cycle'], name='aid_managem_student_ff57d4_idx'),
        ),
        migrations.AddIndex(
            model_name='aidapplication',
            index=models.Index(fields=['status'], name='aid_managem_status_cf23cc_idx'),
        ),
        migrations.AddIndex(
            model_name='aidapplication',
            index=models.Index(fields=['submission_date'], name='aid_managem_submiss_df4234_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aidapplication',
            unique_together={('student', 'cycle')},
        ),
    ]
