# Generated by Django 6.0.2 on 2026-05-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidapplication',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='aid_applications/documents/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='المستندات الداعمة (PDF)'),
        ),
    ]
