# Generated by Django 6.0.2 on 2026-05-14 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_management', '0002_aidapplication_supporting_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidapplication',
            name='auto_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تُحسب تلقائياً بناءً على بيانات الطالب وقواعد التقييم.', max_digits=8, verbose_name='الدرجة التلقائية'),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='auto_score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='تفصيل النقاط لكل بُعد تقييمي.', verbose_name='تفصيل الدرجة التلقائية'),
        ),
        migrations.AlterField(
            model_name='committeereview',
            name='dimension_scores',
            field=models.JSONField(blank=True, default=dict, help_text="مثال: {'income_tier': 10, 'gpa': 5}", verbose_name='درجات التقييم'),
        ),
        migrations.AlterField(
            model_name='committeereview',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'role': 'R'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المراجع'),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='condition',
            field=models.JSONField(blank=True, default=dict, help_text="مثال: {'min': 0, 'max': 3000}", verbose_name='شرط التطبيق'),
        ),
    ]
